tasks:
  - init: psql -f db-init.sql
    name: Initialize DB
  - init: ./gradlew bootJar
    command: ./gradlew bootRun
    name: Run app

image: gitpod/workspace-postgres

ports:
  - port: 8080
    onOpen: open-browser
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
    - fwcd.kotlin