tasks:
  - init: ./gradlew build
    command: ./gradlew bootRun
    name: Run app
  - init: psql -f db-init.sql
    name: Initialize DB

image:
  file: .gitpod.dockerfile

ports:
  - port: 8080
    onOpen: ignore
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot